### ISSUE TITLE
Pictures page

### ISSUE THREAD

**Issue by Sarius11** [DynamiC0de/kredenc#1]
The pictures page linked to landing page. not to It's own gallery

**Comment by ArDrift** [comment]
#### Gallery page implementation: (ac0d589)

* `show:` front matter property + collections (for easier siteleaf integration):
  - memes
  - photos
  - comics

* Gallery page (`show:` gallery):
  - lists pages with `gallery: true`

* On the pages:
  - list corresponding posts from the collections (memes, photos or comics)
